on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run style
      - run: npm run coverage
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["8", "10", "12", "14", "16"]
    name: Test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
